### ISSUE TITLE
[Feature request] Please allow to copy model info text

### ISSUE THREAD

**Issue by ke1ne** [Stackyard-AI/Amuse#11]
Hi there, thank you for your work.
Could you please allow to seelct and copy model info text values?
![image](https://github.com/Stackyard-AI/Amuse/assets/8934421/95a32c87-af2d-42c2-a7fc-e7aad61af32b)

**Comment by saddam213** [comment]
This issue should now be resolved in version v1.1.0
https://github.com/Stackyard-AI/Amuse/releases/tag/v1.1.0

**Comment by ke1ne** [comment]
Thanks!
