### ISSUE TITLE
The app can't download LCM Dreamshaper model.

### ISSUE THREAD

**Issue by JohnClaw** [Stackyard-AI/Amuse#13]
An attempt to download it raises an error.

**Comment by TheyCallMeHex** [comment]
What's the error?

**Comment by saddam213** [comment]
This issue should now be resolved in version v1.1.0
https://github.com/Stackyard-AI/Amuse/releases/tag/v1.1.0

**Comment by JohnClaw** [comment]
> This issue should now be resolved in version v1.1.0

Thanks. Now i can download LCM Dreamshaper. But i encountered the same error when i tried to download SDXL Turbo. Here's a screenshot: 
![image](https://github.com/Stackyard-AI/Amuse/assets/131554379/4aeb082e-42f6-4221-bf59-007b69a06504)

**Comment by saddam213** [comment]
Hey John,

The download links for `SDXL-Turbo` should now be fixed, I have also added a template for `SD-Turbo` :)

Thanks for the bug report :)
