### ISSUE TITLE
Amuse uses iGPU instead of CPU.

### ISSUE THREAD

**Issue by JohnClaw** [Stackyard-AI/Amuse#19]
I run Amuse on amd laptop with integrated graphics. Other AI software like Fastsdcpu and Stable-diffusion.cpp uses laptop's CPU to generate images. But Amuse uses iGPU. It works slower and iGPU temperature raises too high. I choosed CPU in Settings tab and clicked the Save changes button but Amuse refuses to obey and use iGPU. Can it be fixed?
![image](https://github.com/Stackyard-AI/Amuse/assets/131554379/97c23261-e8bd-4763-bbf6-8d37ee2e636f)

**Comment by saddam213** [comment]
If you have already installed a model you can edit the models settings and change the device

![image](https://github.com/Stackyard-AI/Amuse/assets/4353684/a55388cf-e39d-46ed-a681-c0a6089ac000)

**Comment by saddam213** [comment]
If you are running on CPU I would suggest cloning the `TAESD` repo, it will be much faster for you

https://huggingface.co/deinferno/taesd-onnx

And setting the `VaeEncoder` and `VaeDecoder` in Advanced Settings

![image](https://github.com/Stackyard-AI/Amuse/assets/4353684/244349d5-9493-4b28-b6ce-558b095aaf90)
